version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "soundcore-lib/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "bluetooth-lib/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "src-tauri/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
