[package]
name = "soundcore-lib"
version = "0.1.0"
edition = "2021"
[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
bluetooth-lib = { path = "../bluetooth-lib/" }