[package]
name = "soundcore-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.23.0", features = ["time", "macros", "rt-multi-thread"] }
async-trait = "0.1.59"
thiserror = "1.0.37"
bluetooth-lib = { path = "../bluetooth-lib/" }
log = "0.4.17"