name: 'Combine PRs'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: GHA-combine-PRs
        uses: vic1707/GHA-combine-PRs@1.1.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-prefix: dependabot/
          combine-branch-name: combine-PRs
          ignore-label: nocombine
          must-be-green: true
          always-recreate: false
          draft: false
          min-prs: 4