name: 'Build latest commit'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: true
      matrix:
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: ⚡ Set short SHA ENV
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

      - name: ⏬ Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: ⚡ Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: ⏬ Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: ⏬ Enable corepack and install
        run: corepack enable && corepack install

      - name: 🔄 Setup yarn in node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: ⏬ Install Ubuntu dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 📥 Install Node Dependencies
        run: yarn --frozen-lockfile

      - name: ⏬ Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: 🔨 Build
        uses: tauri-apps/tauri-action@v0
        id: tauri-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename binary for windows
        if: matrix.platform == 'windows-latest'
        run: ren "target\release\Soundcore Manager.exe" SoundcoreManager-${{ matrix.platform }}-${{ env.SHORT_SHA }}.exe

      - name: ⏫ Upload Build Artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: SoundcoreManager-${{ matrix.platform }}.exe
          path: target\release\SoundcoreManager-${{ matrix.platform }}-${{ env.SHORT_SHA }}.exe
